### ISSUE TITLE
Prefix urls with the language to improve SEO

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/gobuffalo#133]
The docs are only indexed in english. To improve the SEO, it can be a good thing to have different URLs for the french and future versions.

For instance, https://gobuffalo.io/docs/new-project can still be the english (default) version, and the french version will be https://gobuffalo.io/fr/docs/new-project

**Comment by hubyhuby** [comment]
I plan to use translation later with buffalo, and this type of urls is compulsory for SEO.
Other url type that google like aswell are fr.gobuffalo.io, es.gobuffalo.io  ...
Related question: Could this mechanisme of subfolder language be automated in a way with the buffalo generator ?

**Comment by stanislas-m** [comment]
@hubyhuby I plan to change the i18n middleware a bit, to allow customized extractors for the language:
- Cookie
- Session
- URL param, maybe (?lang=en)
- URL prefix (/en/, /fr/)
- subdomains (en.domain.io, fr.domain.io)
- Custom extractor using an interface?

I'd like to have a way to set priority for extractors too (first session, then cookie, and so on). Keeping the same default as now should be enough to keep back-compatibility.

**Comment by hubyhuby** [comment]
Hi @stanislas-m ,
I have not experienced for now the i18n feature in Buffalo.
On a SEO perspective what I have read is that the best practices in order are : 
-Have several top domains : gobuffalo.fr gobuffalo.de ...
-Have subdomain like this fr.gobuffalo.io de.gobuffalo.fr ....
-Have a subfolder gobuffalo.io/fr gobuffalo.io/de

As I understand the "?lang=en" is not something search engines like. As of today...

My personal experience with the last website launch 4 motnhes ago, is that subdomains like "en.gobuffalo.io" works well in google. If I am in spain and try to reach my french website it will show on google "en.gobuffalo.io" (and not "gobuffalo.io" ) in first page.

Conerning your technical question, as I didn t used it yet, I don t have a vlue ;)

**Comment by stanislas-m** [comment]
@hubyhuby I've reworked the i18n middleware a bit here: https://github.com/gobuffalo/buffalo/pull/957

It should allow to manage the subfolder way, and make the language finding easier to extend. I'm not sure Buffalo allows to run multiple domains / subdomains from now, but if not you can ask for this feature in the Buffalo repo. :)

**Comment by stanislas-m** [comment]
Since this specific point is resolved, I close this issue. @hubyhuby if you want a support for subdomains, please add an issue in the buffalo repo. :)
