### ISSUE TITLE
Space for content on the website is small

### ISSUE THREAD

**Issue by omgitsjoao** [gobuffalo/gobuffalo#149]
So while getting started with buffalo, I went to the documentation site to read the guides, while doing so I felt a bit uncomfortable with the sizing of the content view, and it might be a bug rather than a personal thing.

Running on Firefox 58.0.1 (64-bit) with a display of 14" at resolution of 1366x768 it renders as:

![screenshot](https://user-images.githubusercontent.com/5256711/35756714-6e4e8924-0853-11e8-9d42-f62d9e216025.png)

Seems the "Buffalo - Rapid Web Development in Go" is taking too much space on the navbar,  in such, when scrolled it does not collapse into a thin navbar. Removing the "Rapid Web Development in Go" does the job as seen:

![screenshot](https://user-images.githubusercontent.com/5256711/35756839-e6a0fd6c-0853-11e8-932c-1e67ff4d511b.png)

Also the footer could be there but not fixed, just at the bottom of each page saving more space.

**Comment by stanislas-m** [comment]
@omgitsjoao It should be better now. :)
