### ISSUE TITLE
Running example goth on port 8080

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/gobuffalo#167]
I runned a second time the example from scratch using linkedin instead of github.
And same thing happen if I am not on 8080 it doesn t work.
mMany people can be blocked testing locally because of the port not beeing opened.
The default 3000 if not opened on your router (ex you are at the office), will block the authentication.
Therefore it could be worth noting on the blog to try to run it on 8080 like this :

PORT=8080 buffalo dev

**Comment by stanislas-m** [comment]
@hubyhuby If you already have an app running on the 3000 port, that's quite normal it's not working. The port you propose will have the same problem behind a router, it depends on your config (and we can't enumerate all possible configs).
