### ISSUE TITLE
Add installation from release packages docs

### ISSUE THREAD

**Issue by stanislas-m** [gobuffalo/gobuffalo#174]
The current docs only explain how to install buffalo from the source. Since we now provide pre-compiled versions, we should provide docs on this installation way.

**Comment by markbates** [comment]
This is related to https://github.com/gobuffalo/buffalo/pull/934

Now that all the templates for things like new app generation are stored with packr, and that sqlite is now opt-in, we can absolutely recommend using the bins are the primary source of install.

**Comment by stanislas-m** [comment]
Done.
