### ISSUE TITLE
Add description metatag for SEO

### ISSUE THREAD

**Issue by philipithomas** [gobuffalo/gobuffalo#19]
Google results are unclear:

<img width="595" alt="screen shot 2017-01-27 at 11 31 02 am" src="https://cloud.githubusercontent.com/assets/1312414/22384668/31b1bc28-e484-11e6-839a-b3e78dd04677.png">

Adding description metatags would help.

**Comment by stanislas-m** [comment]
![image](https://user-images.githubusercontent.com/1911803/34920848-c6610ef4-f979-11e7-8df6-6b403be9c36b.png)

It seems fine now. :)
