### ISSUE TITLE
Add documentation for Flash usage

### ISSUE THREAD

**Issue by bscott** [gobuffalo/gobuffalo#20]

**Comment by apaganobeleno** [comment]
I think i can help with this one @bscott i'll keep you posted :)

**Comment by bscott** [comment]
@apaganobeleno Hey, I was going to start on this, let me know what you plan on?

:)

**Comment by apaganobeleno** [comment]
i think it was already done, no ? sorry for delaying you.

**Comment by markbates** [comment]
Yep, this is all done. Closing this issue.
