### ISSUE TITLE
Create a section exclusively for building

### ISSUE THREAD

**Issue by markbates** [gobuffalo/gobuffalo#22]
Include the `-z` flag and the new `-e` flag.

**Comment by stanislas-m** [comment]
@markbates I can do this one if you want.

**Comment by markbates** [comment]
That would be great!

The `-z` flag doesn't do anything any more since we got rid of `go.rice`.

**Comment by stanislas-m** [comment]
@markbates Can you check the linked merge request?

**Comment by markbates** [comment]
Yep. It's on my list for today.

**Comment by stanislas-m** [comment]
Thanks!
