### ISSUE TITLE
Logo Overlaps Player Controls in Full Screen Videos

### ISSUE THREAD

**Issue by zikes** [gobuffalo/gobuffalo#247]
From the video on generating resources at https://gobuffalo.io/en/docs/generators:

![screenshot from 2018-06-04 22-38-59](https://user-images.githubusercontent.com/410905/40954049-4a788de2-6848-11e8-8fe8-0aecedebfbb8.png)

The logo makes the volume, gear, and full screen button inaccessible while the video is in full screen mode.

Chrome 67.0.3396.62 on Linux

**Comment by duffn** [comment]
This seems to have been corrected. The logo no longer overlaps the controls in the videos I tested.

<img width="1440" alt="screen shot 2018-08-31 at 5 29 29 am" src="https://user-images.githubusercontent.com/3457341/44910055-f94b9f00-acde-11e8-92a9-91d3aa596db8.png">

**Comment by stanislas-m** [comment]
Please reopen if you still have the issue. :)
