### ISSUE TITLE
Fix go get command

### ISSUE THREAD

**Issue by gepser** [gobuffalo/gobuffalo#25]
Here https://github.com/gobuffalo/gobuffalo/blob/master/templates/docs/getting-started.md
we have the **buffalo** word duplicated

`
$ go get -u github.com/gobuffalo/buffalo/buffalo
`

it should be like this:

`
$ go get -u github.com/gobuffalo/buffalo
`

**Comment by markbates** [comment]
Actually that is correct. That's not a duplicate word, but rather a sub package containing the binary.

**Comment by gepser** [comment]
Thanks, my mistake.
