### ISSUE TITLE
users/index.html: line 32: pagination: unknown identifier

### ISSUE THREAD

**Issue by drnic** [gobuffalo/gobuffalo#262]
I'm following along the https://gobuffalo.io/en/docs/generators tutorial, and the generated `users/index.html` includes the following:

```html
<div class="text-center">
  <%= paginator(pagination) %>
</div>
```

But when I view http://127.0.0.1:3000/users I get a 500:

```
users/index.html: line 32: pagination: unknown identifier
```

What do I need to add to my code to get the `pagination` helper?

**Comment by stanislas-m** [comment]
@drnic I've updated the resource example (which was moved to https://gobuffalo.io/en/docs/resources#generator).

`pagination` is a variable you set in your action, which contains a `Paginator`. See the updated example to see how to get a `Paginator` from a pop query. :)
