### ISSUE TITLE
Missing Docs Fixture

### ISSUE THREAD

**Issue by kteb** [gobuffalo/gobuffalo#295]
This is a real helpful and I didn't find anything on the website about it.

**Comment by duffn** [comment]
I'll take a stab at this one.

**Comment by kteb** [comment]
Cool, you'll find few interesting information here: 

https://blog.gobuffalo.io/buffalo-v0-12-0-released-c8412c7198f0 (one of the last paragraph) 
https://github.com/gobuffalo/suite (at the end of the readme)

and I guess the best place to write it is https://gobuffalo.io/en/docs/testing
