### ISSUE TITLE
didn't find layout plugin from the video tutorial

### ISSUE THREAD

**Issue by Hkyx** [gobuffalo/gobuffalo#296]
Hi,

trying to follow the buff.la video tutorial but seems didn't get the plugin for layout and don'T see it on the website, did I miss something?

regards,

hk

**Comment by kteb** [comment]
Hi hk, 

You can find it here; (https://github.com/markbates/buffalo-bootstrap) and it's also on the project website (https://gobuffalo.io/en/docs/plugins).

Regards,
Kerim

**Comment by Hkyx** [comment]
Thank your @kteb  
Finded just after posted, but think the video is not including all the different needed steps. 
May be it's not the goal of the video, but it can be a good start to use buffalo to make a video about all of this kind of stuff :) (as a starter developper, it's not easy all time).

Regards,
Hk
