### ISSUE TITLE
I can't install it locally

### ISSUE THREAD

**Issue by fooflare** [gobuffalo/gobuffalo#3]
First of all, thanks for the buffalo project and the hard work to make everything easier.

My Go environment is: 
  * go version go1.7.4 linux/amd64
  * glide version 0.13.0-dev

I am trying to install the web locally but I have a problem with glide. When I run ```glide install```, I get:
```[WARN]	Lock file may be out of date. Hash check of YAML failed. You may need to run 'update' ```
but it seems to install successfully the dependencies. When I try to build it, I get:
```
# github.com/gobuffalo/gobuffalo/actions
actions/render.go:23: unknown render.Options field 'FileResolverFunc' in struct literal
```

Now, if I run: ```glide update```, as recommended in the warning, I get another error:
```
[ERROR]	Failed to set version on github.com/gobuffalo/buffalo to 6a260cd30f2c6e2083be41af4ad43dd46d551074: Unable to update checked out version
```
The curious thing is that when I run the ```glide install``` the buffalo 
version installed was: ```e4fadf1c6403eea0c9d2047adfb40ccdbbc7bcf4```

**Comment by markbates** [comment]
That would probably be because I forgot this project was using glide, and I haven't been updating it! Whoops!

**Comment by markbates** [comment]
Ignore the glide files and just do 

go get -v -t ./... that should work.

**Comment by fooflare** [comment]
Great! That worked fine, thanks.

**Comment by markbates** [comment]
Sorry about that. I was using glide, because Heroku needed dep management, but now I just use 'buffalo build' locally and push a binary.

**Comment by fooflare** [comment]
Oh, no problem. It is completely normal that these things happen :-). I like more this method. Now everything is working. Thanks again.
