### ISSUE TITLE
has_one bad example

### ISSUE THREAD

**Issue by kteb** [gobuffalo/gobuffalo#401]
Hi all,

When I see 

```go
type User struct {
  ID           uuid.UUID
  Email        string
  Password     string
  Books        Books     `has_many:"books" order_by:"title asc"`
  FavoriteSong Song      `has_one:"song" fk_id:"u_id"`
  Houses       Addresses `many_to_many:"users_addresses"`
}

type Song struct {
  ID      uuid.UUID
  Title   string
  UserID  uuid.UUID   `db:"u_id"`
}
```

It doesn't show the favorite song of the user, but maybe "the biggest fan" of the song or something like that.  I know that it is not easy to find a relevant and simple example for 1-1 relationship but this one was really confusing for me (it should more be has_many in the song and belongs_to in the user) as a song could be the favorite song of more than one user. But we force a user to have only one favorite song. It created me confusion between has_one and belongs_to when I was reading it (I needed belongs_to and thought has_one could be the good candidate). I guess also than the belongs_to works with the has_one (in the reverse way). 

So the goal of the issue is finding a 1-1 relationship that make sense and than update the doc (or I'm the only one that finds it as not a very good example).

**Comment by stanislas-m** [comment]
https://gobuffalo.io/fr/docs/db/relations/onetoone/
