### ISSUE TITLE
Create new project outside of the GOPATH

### ISSUE THREAD

**Issue by anidotnet** [gobuffalo/gobuffalo#414]
I am trying to create an api project outside of the GOPATH with module support and I am not able to create it using `buffalo new` command. Even if I created a new project  inside GOPATH as suggested and then take it outside, I am unable to run `buffalo dev`.

Is there any way I can create a new project outside of GOPATH? I can't find any instruction in documentation.

**Comment by stanislas-m** [comment]
See https://gobuffalo.io/en/docs/gomods/
