### ISSUE TITLE
Cannot install, "Not a branch error" with go get -u -v github.com/gobuffalo/buffalo/buffalo  

### ISSUE THREAD

**Issue by moshahmed** [gobuffalo/gobuffalo#430]
First page of google results for "golang buffalo install" point to this non working example:
[And nobody has reported this on stackoverflow?]
```
$ go get -u -v github.com/gobuffalo/buffalo/buffalo  
    cd $HOME/go/src/golang.org/x/text; git pull --ff-only
   You are not currently on a branch.
  Please specify which branch you want to merge with.
```

**Comment by stanislas-m** [comment]
This isn't a buffalo error, it means you've made changes in `$HOME/go/src/golang.org/x/text` and the go toolchain tries to update it but failed. Remove this dir or ensure it's in a clean state.
