### ISSUE TITLE
Using Go Templates

### ISSUE THREAD

**Issue by jhabdas** [gobuffalo/gobuffalo#439]
So I'm looking at your [templating docs](https://gobuffalo.io/en/docs/templating) and there some notes suggesting Plush isn't required and honestly I never in a million years would consider using it because it isn't designed for humans. How can we switch to Go?

By to add a header in plush (from the examples):

```
<h1><%= name %>
```

To do the same in Go templates:

```
<h1>{{ .name }}
```

Please type both of those out more than once and let me know what human would ever choose the former. By the way, Vimeo is blocked in Indonesia. Please consider hosting your own videos. You can use Keybase for this if you need to.

**Comment by markbates** [comment]
I’m sorry, but this is about one of the rudest tickets I’ve seen. You could’ve just asked asked how to use Go templates, but instead you decided to insult the hard work of a lot of people who do this for FREE. 

You don’t have to like Plush templates, but you also don’t have to be this rude and insulting. 

Read https://golang.org/conduct and try to treat people with respect.

**Comment by jhabdas** [comment]
What, I'm supposed to kiss ass because someone made something for "FREE". Give me break, guy. You heard the feedback. Now it's yours to cherish.

**Comment by stanislas-m** [comment]
You could’ve just asked asked how to use Go templates. Just that.

**Comment by jhabdas** [comment]
I could have, but that wouldn't have been sincere. Those plush templates were an immediate turn off. If the maintainer has 18 years of experience surely they know how to interpret feedback however delivered.

**Comment by markbates** [comment]
First off, constructive criticism is always welcome, but you didn’t do that you served up a heavy dose of insults. No one asked you to kiss ass. Your ticket could’ve been, “I would like to use Go templates instead of Plush, how do I do that?”. But no, you came and spent a long time insulting people, and you still do. 

You don’t have to like Plush, but you don’t have to insult those that wrote it.

**Comment by u007** [comment]
im on the reverse side, plush is so much more human in term of rendering.
i even use it for generating codes, and scaffolds. doing that in go templating is such a pain!
