### ISSUE TITLE
buffalo_0.14.0_linux_amd64.tar.gz doesn't have buffalo-no-sqlite

### ISSUE THREAD

**Issue by yokkora** [gobuffalo/gobuffalo#447]
https://gobuffalo.io/en/docs/installation/

![スクリーンショット 2019-03-11 21 30 18](https://user-images.githubusercontent.com/3676947/54124193-ff1bfd00-4444-11e9-8425-2687f0467738.png)

There is no buffalo-no-sqlite.

```bash
#tar -xvzf buffalo_0.14.0_linux_amd64.tar.gz
LICENSE.txt
README.md
buffalo
```

**Comment by stanislas-m** [comment]
Fixed with #448.
