### ISSUE TITLE
Installation procedure with plugins (new buf 0.14.2)

### ISSUE THREAD

**Issue by hubyhuby** [gobuffalo/gobuffalo#463]
Just had a test run with the new Buffalo 0.14.2 on a fresh install Ubuntu Linux.
The current documentation doesn t seem to describe the new method needed to install buffalo. 
There are informations , but the "getting started" page doesn t get you to a working environement. 
Especially the "getting started" doesn t guide you through pluggin installation.
https://gobuffalo.io/en/docs/getting-started/installation
-----
So we have to guess, I appologies if I guessed wrong.... but here is how far I got :
I had to chmod 777 /usr/lib/go-1.12/bin to have the plugin getting to install. It was first blocking on the plugin for plugins : 
"DEBU[2019-04-07T16:25:01+02:00] Exec: go get github.com/gobuffalo/buffalo-plugins
go get github.com/gobuffalo/buffalo-plugins: open /usr/lib/go-1.12/bin/buffalo-plugins: permission denied"

So then I could do : go get -u -v github.com/gobuffalo/buffalo-plugins

But the plugins never got into the mind of the main buffalo binary ... and I cannot do "buffalo pop create" or "buffalo plugins" ...
I had to do "buffalo-plugins plugins install github.com/gobuffalo/buffalo-pop"
Then I can do  "buffalo-pop pop create"

Sorry for this maybe confusing bug, which is a mix of not understanding the new plugin and not finding the documentation.

Following this described path, I got a running buffalo environement (without plugins command linked to the main buffalo). I am also wondering if the installation of the plugins in "/usr/lib/go-1.12/bin/" is a normal behaviour. When I will upgrade to go 1.13 , will this still work .

PS : Clara is a very nice software that was very helpfull.

**Comment by hubyhuby** [comment]
I now have a fully working environment installing again with 0.14.3.
With 0.14 it seems you need to set export PROJBIN=/home/ME/Documents/projects/bin

Installing 0.14.3 , it seems that Yarn is compulsory.
If not using yarn I get the following NPM error : 

DEBU[2019-04-14T10:31:17+02:00] LookPath: yarnpkg
DEBU[2019-04-14T10:31:17+02:00] Exec: npm install -g yarn
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! path /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!  { Error: EACCES: permission denied, access '/usr/local/lib/node_modules'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/yann/.npm/_logs/2019-04-14T08_31_28_188Z-debug.log
Usage:
  buffalo new [name] [flags]

Flags:
      --api                  skip all front-end code and configure for an API server
      --ci-provider string   specify the type of ci file you would like buffalo to generate [none, travis, gitlab-ci] (default "none")
      --config string        config file (default is $HOME/.buffalo.yaml)
      --db-type string       specify the type of database you want to use [cockroach, mysql, postgres, sqlite3] (default "postgres")
      --docker string        specify the type of Docker file to generate [none, multi, standard] (default "multi")
  -d, --dry-run              dry run
  -f, --force                delete and remake if the app already exists
  -h, --help                 help for new
      --module string        specify the root module (package) name. [defaults to 'automatic']
      --skip-config          skips using the config file
      --skip-pop             skips adding pop/soda to your app
      --skip-webpack         skips adding Webpack to your app
      --skip-yarn            use npm instead of yarn for frontend dependencies management
      --vcs string           specify the Version control system you would like to use [none, git, bzr] (default "git")
  -v, --verbose              verbosely print out the go get commands
      --with-dep             adds github.com/golang/dep to your app

ERRO[0221] Error: exit status 243

**Comment by markbates** [comment]
This isn’t a buffalo issue, it’s a node one. https://docs.npmjs.com/resolving-eacces-permissions-errors-when-installing-packages-globally

**Comment by hubyhuby** [comment]
Other users have similar issues with the plugin detection in Buffalo here :
https://gophers.slack.com/conversation/C3MSAFD40/p1556219437010800
