### ISSUE TITLE
Ranging Over Parameters documentation: doesn't work out of the box

### ISSUE THREAD

**Issue by MatthiasRMS** [gobuffalo/gobuffalo#487]
Hi,

I've been looking for a way to print all parameters received in the body of a POST request.
I've stumbled upon:
https://gobuffalo.io/docs/context#ranging-over-parameters
https://github.com/gobuffalo/gobuffalo/blob/master/templates/docs/context.md

However, when adding this snippet in a handler, it raises an error:
`actions/home.go:8:26: undefined: url`

I think this is making things complicated for a newcomer, and since this is a pretty standard need, it would be worth fixing it. I'd be happy to provide a PR but I couldn't find the right way to make this work 🤷‍♂

**Comment by stanislas-m** [comment]
Fixed with #492.
