### ISSUE TITLE
Running tasks error on windows

### ISSUE THREAD

**Issue by spankie** [gobuffalo/gobuffalo#52]
Good day,
I used buffalo for an app, which works fine, but on windows, when i try running `buffalo tasks db:seed` it returns an error saying 'grifts' directory could not be found. I'm sure i am in the right directory, i even did `buffalo task init` and it places example.go inside the grifts directory, but running the seed task does not find the directory. Apart from this everything else works fine...

I'd really appreciate if you can help me identify what's wrong. THANKS...

**Comment by markbates** [comment]
I've been looking for this ticket for a day now. I couldn't find it on the https://github.com/gobuffalo/buffalo or https://github.com/markbates/grift repos. :)

I can't reproduce this on Windows or Mac OS.

Using the latest version of Buffalo `0.9.0` and the latest version of `grift` I ran the following:

```
$ cd %GOPATH%/src/github.com/markbates
$ buffalo new coke
$ buffalo t list

Buffalo version v0.9.0

buffalo task db:seed    # 
buffalo task routes     # 
```

Everything worked fine. 

Can you perhaps give me more information about what Go version you're using, which version of Buffalo you are using, etc...

Like I said, I can't reproduce using the `master` branches of these libraries.

**Comment by spankie** [comment]
This is my go version and buffalo version.
`
Buffalo version v0.9.0
go version go1.8.1 windows/amd64
`
I got it working by resolving the separator `/src/` to windows style "\". I made a pull request if it is okay.

**Comment by markbates** [comment]
Thanks for the PR.
