### ISSUE TITLE
Add "Features at a glance" or "Comparison" page

### ISSUE THREAD

**Issue by corylanou** [gobuffalo/gobuffalo#61]
The purpose of this page would be to give developers a way to evaluate if Buffalo is ready for them.

Having a "Features at a glance" would be a great start, but ultimately, showing a feature comparison of Buffalo to Rails would be better.

This isn't about showing which framework/ecosystem is better, but more about allowing a developer to make an informed decision on what tools they are going to be able to get when they choose Buffalo.  It would also help identify any large technology gaps that still need to be added.

**Comment by stanislas-m** [comment]
Fixed with #85.
