### ISSUE TITLE
Having trouble contributing

### ISSUE THREAD

**Issue by wideawake** [gobuffalo/gobuffalo#64]
Hi Mark,

I just cloned the repo and run `buffalo setup`, everything ok except that the app is not loading any assets:

`http://localhost:3000/assets/application.css => 404`

Can you please help me so that I can contribute to the docs?

Thank You

**Comment by rgerardi** [comment]
Earlier today, on Slack, Mark recommended this article: [Contributing to Open Source Git Repositories in Go](https://splice.com/blog/contributing-open-source-git-repositories-go/). It shows to how to setup the environment to contribute to Go projects. It resolved the issue for me.
